services:
  - type: web
    name: your-service-name
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DB_SERVER
        value: 201.237.248.149
      - key: DB_NAME
        value: PracticaUtilidades
      - key: DB_USER
        value: pruebas2016
      - key: DB_PASSWORD
        value: pruebas2016
      - key: SECRET_KEY
        value: your_secret_key
