services:
  - type: web
    name: your-service-name
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DB_SERVER
        value: your_db_server
      - key: DB_NAME
        value: your_db_name
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: SECRET_KEY
        value: your_secret_key
